export const customerData = {
    fullName: "",
    dateOfBirth: "",
    gender: "",
    religion: "",
    phoneNumber: "",
    country: "",
    state: "",
    city: "",
    area: "",
    region: "",
    email: "",
    password: "",
    role: "ROLE_USER",
    userType : "CUSTOMER",
    userImage: null,
}